---

- name: Get the version information of the latest release of kops
  uri:
    url: "{{ kops_github_api }}/releases/latest"
    return_content: true
    body_format: json
  register: kops_get_latest_version

- name: Ensure the kops_version variable is set
  set_fact:
    kops_version: "{{ kops_get_latest_version.json.tag_name | regex_replace('^v', '') }}"
