---

- name: Check the state of the new kops package
  stat:
    path: "{{ kops_install_dir }}/kops"
  register: kops_check_installed

- name: Fail play if kops is not installed as expected
  assert:
    that:
      - kops_check_installed.stat.exists
      - kops_check_installed.stat.islnk
    fail_msg: kops was not installed as expected, it is likely something went wrong.
    success_msg: kops has been installed as expected.

- name: Check the kops binary version matches the expected version
  shell: >
    set -o pipefail && \
      {{ kops_install_dir }}/kops version | \
      awk '{ print $2 }' | sed 's/^v//'
  args:
    executable: "{{ kops_check_bash_path.stdout_lines[0] }}"
  changed_when: false
  failed_when: false
  register: kops_check_installed_version

- name: Fail play if kops is not the expected version
  assert:
    that:
      - kops_check_installed_version.stdout_lines[0] == kops_version
    fail_msg: Installed kops version is not as expected, it is likely something went wrong.
    success_msg: Installed kops version is as expected.
